---
#every ansible playbook start with three dashes
-
#this minus in yaml indicate a list of items. the playbook contain a list
#of play with each play as dictionary

#Target: where our play will run 
  hosts: worker
  tasks:
    - name: verifying that app/database are running or not. 
      shell: if ps -eaf| egrep 'httpd'| grep -v grep > /dev/null; then echo 'process_running';else echo 'process_not_running';fi
      ignore_errors: true
      register: appr_proc_check
    - debug: msg="{{appr_proc_check}}"