---
#every ansible playbook start with three dashes
-
#this minus in yaml indicate a list of items. the playbook contain a list
#of play with each play as dictionary

#Target: where our play will run 
  hosts: worker
  # task: the list of task that will be executed with in the play 
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true
      notify: Start Apache
    - name: install latest package of firewalld
      yum:
        name: firewalld
        state: latest
      
    - name: start and enable firewall
      service:
        name: firewalld
        state: started
        enabled: true  
      notify: Firewall Started
    - name: permit a rule in firewalld http
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
    - name: create a simple html web page
      copy:
        content: "welcome to ansible learning module \n"
        dest: /var/www/html/index.html
    - name: Define a webserver name
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: ServerName www.client1.example.com:80
        insertafter: "#ServerName"
    - name: Update the entry in /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 192.168.0.12 www.client1.example.com

  handlers:
    - name: Firewall Started
      mail:
        host: smtp.gmail.com  
        port: 587
        username: gopal1409
        password: xyz
        sender: gopal1409@gmail.com
        to: yum@gmail.com
        subject: Report for {{ ansible_hostname }}
        body: 'Server{{ ansible_hostname }} firewalld started'
      delegate_to: localhost
    - name: Start Apache
      service:
        name: httpd
        state: started      