---
#every ansible playbook start with three dashes
-
#this minus in yaml indicate a list of items. the playbook contain a list
#of play with each play as dictionary

#Target: where our play will run 
  hosts: worker
  # task: the list of task that will be executed with in the play 
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    perl_pkg: perl
    rule: http
  tasks:
    - name: install package
      yum:
        name:
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
          - "{{ perl_pkg }}"
        state: latest
        when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")
    - name: start and enable httpd
      service:
        name: "{{ web_pkg }}"
        state: started
        enabled: true 
    - name: start and enable firewall
      service:
        name: "{{ firewall_pkg }}"
        state: started
        enabled: true  
      notify: Firewall Started
    - name: permit a rule in firewalld http
      firewalld:
        service: "{{ rule }}"
        permanent: true
        state: enabled
        immediate: yes
    - name: create a simple html web page
      copy:
        content: "welcome to ansible learning module \n"
        dest: /var/www/html/index.html
      
    - name: Define a webserver name
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: ServerName www.client1.example.com:80
        insertafter: "#ServerName"
    - name: Update the entry in /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 192.168.0.12 www.client1.example.com
