---
#every ansible playbook start with three dashes
#this minus in yaml indicate a list of items. the playbook contain a list
#of play with each play as dictionary

#Target: where our play will run 
    - name: verifying that app/database are running or not. 
      shell: if ps -eaf| egrep 'httpd'| grep -v grep > /dev/null; then echo 'process_running';else echo 'process_not_running';fi
      ignore_errors: true
      register: appr_proc_check
    - debug: msg="{{appr_proc_check.stdout}}"
    - name: Decision Point to start patching
      fail:
        msg="{{ inventory_hostname }} have running application please stop first then attempt patching"
      when: appr_proc_check.stdout == "process_running"
    - name: Intiate patching
      yum:
        name: kernel
        state: latest
    - name: Current Kernal Version
      shell: uname -r
      register: curr_ker
    - debug: msg="{{curr_ker.stdout}}"
    - name: check if reboot is required or not. 
      shell: kernel_new=$(rpm -qa --last kernel | head -1| awk '{print $1}'| sed 's/kernal-//g'); kernel_now=$(uname -r); if [[$kernel_new != $kernel_now]]; then echo "reboot is required"; else echo "reboot is not required";fi
      ignore_errors: true
      register: reboot_check
    - debug: msg="{{reboot_check.stdout}}"  
    - name: Reboot the system after patching
      shell: "shutdown -r now" 
      async: 1
      poll: 0
    - name: wait for the system to come up
      pause: 
        minutes: 1
    - name: new kernal version
      shell: uname -r
      register: new_ker
    - debug: msg="new kernal version is {{new_ker.stdout}}and old kernel version was {{ curr_ker.stdout }}"  
    
